name: MusicRooms Tests frontend

on:
  push:
    branches:
      - main
      - development
      - websockets

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12]

      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - name: Install dependencies
          run: npm i
        - name: Run tests
          run: npm test -- --coverage
